# Generated by Django 5.2.5 on 2025-08-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parents',
            new_name='parent',
        ),
    ]
