# Generated by Django 5.2.5 on 2025-08-25 18:54
from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=CKEditor5Field('Content', config_name='default'),  # Coincide con tu modelo
        ),
    ]
